services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pgdatabase
    ports:
      - '5432:5432'
    volumes:
      - ./pgdatabase:/var/lib/postgresql/data
